name: camorama
description: A Flutter camera app
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.0.3

  camera: ^0.10.0+4
  camera_web: ^0.3.5    # UPDATED camera_web version to latest stable (fixes platformViewRegistry issue)
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
